name: "Check and Update Docker Image"
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cronjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Script
      run: ./last_stable.py
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
